name: VAYUZ Bhuvanesh S3 deployment testing

on:
  push:
    branches:
      - master # Change this to your main branch 

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18 # Use the 
      
      - name: Install dependencies
        run: npm install
      
      - name: Build bundle
        run: npm run build
      
      - name: Upload to S3
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws s3 cp public/ s3://anarock-staging/panel/ --recursive --exclude "node_modules/*" --acl public-read
        env:
          AWS_DEFAULT_REGION: us-east-1 # Change this to your desired region